# dein本体。基本は repo に github のリポジトリを設定するだけでよい
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'posva/vim-vue'

# nerdcommenter : コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# vim-gitgutter : gitの差分を左端に表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# NERDTreeの設定
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    " NERDTreeの自動起動（ファイル名指定時にはNERDTreeを表示しない）
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
    " Ctrl + n で 起動/終了
    map <C-n> :NERDTreeToggle<CR>
'''

# onedarkの設定
[[plugins]]
repo = 'joshdick/onedark.vim'

